# https://taskfile.dev

version: "3"

tasks:
  default:
    deps:
      - build
    cmds:
      - ./secret-santa 2>&1 | tee /tmp/server.log &
      - elm-live www/Main.elm -- --output=dist/main.js --debug

  serve:
    cmds:
      - ./secret-santa 2>&1 | tee /tmp/server.log

  frontend:
    cmds:
      - mkdir -p dist
      - elm make www/Main.elm --output dist/main.js

  backend:
    cmds:
      - go build

  watch:
    cmds:
      - elm-live www/Main.elm -- --output=dist/main.js --debug

  build:
    deps:
      - frontend
      - backend
