# https://taskfile.dev

version: "3"

tasks:
  default:
    deps:
      - build
    cmds:
      - task serve &
      - task watch

  serve:
    cmds:
      - ./secret-santa 2>&1 | tee /tmp/server.log

  frontend:
    cmds:
      - mkdir -p dist
      - elm make www/ServerPage.elm --output dist/server_page.js
      - elm make www/Index.elm --output dist/index.js

  backend:
    cmds:
      - go build

  watch:
    cmds:
      - elm-live www/ServerPage.elm --no-server -- --output=dist/server_page.js --debug &
      - elm-live www/Index.elm --no-server -- --output=dist/index.js --debug

  build:
    deps:
      - frontend
      - backend
